#!/usr/bin/env ruby

require 'rubygems' # needed for Ruby 1.8
$LOAD_PATH << './lib'
$LOAD_PATH << './app'
Dir["./app/*.rb"].each { |file| require file }

options = ArgumentParser.parse(ARGV)

OrbLogger.verbose = true if options[:verbose]

parser = case options[:parser]
  when "weather" then WeatherParser.new(options[:city])
  when "delay" then DelayParser.new(options[:origin], options[:destination])
  when "gmail" then GmailParser.new(options[:account], options[:password])
  when "nodeci" then NodeciParser.new(options[:monitor])
end

orb = Orb.new(options[:port])
while true
  parser.green? ? orb.green(:on) : orb.red(:on)
  OrbLogger.log("Sleeping for #{options[:interval]} seconds")
  sleep options[:interval]
end
